//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicRPG.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicRPG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ╔═══════════════════════════════════════╗
        ///║       ___                             ║
        ///║     ,&apos;._,`.                           ║
        ///║    (-.___.-)                          ║
        ///║    (-.___.-)                          ║
        ///║    `-.___.-&apos;                          ║
        ///║     ((  @ @|              .           ║
        ///║      \   ` |         ,\   |`.    @|   ║
        ///║     __`.`=-=mm===mm:: |   | |`.   |   ║
        ///║    (    `-&apos;|:/  /:/  `/  @| | |   |,  ║
        ///║     \ \   / /  / /         @| |   &apos;   ║
        ///║     |\ \ / /| / /            @|       [stringa troncata]&quot;;.
        /// </summary>
        internal static string AsciiArt_Bard {
            get {
                return ResourceManager.GetString("AsciiArt.Bard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a                    ++                   
        ///                 __)(__                 
        ///_________+______/      \______+_________
        ///  __--   |       R.I.P.       |-_-- __  
        ///_-- -    | ___ __________ ___ |         
        ///-_-- __  || | | | {|    /| | || __---   
        /// --__-   || | | | {|   /|| | ||--       
        ///         || | | | {|  /||| | ||__--     
        /// __-- -__|| | | | {| |}||| | ||--   __--
        ///         ||_|_|_|_{| |}|||_|_||  -__    
        /// --__-  -|| | | | {&amp; |}||/ | ||---   __-
        ///         || | | | {| |}|/| | ||-__      
        ///--   __- [stringa troncata]&quot;;.
        /// </summary>
        internal static string AsciiArt_Gate {
            get {
                return ResourceManager.GetString("AsciiArt.Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ╔═════════════════════════════════════╗
        ///║                                     ║
        ///║                             A       ║
        ///║                 ,==.       /\\      ║
        ///║     ,-. ,-.    /( `|\     /  \\     ║
        ///║    (   `-. `. /,+./,,).../___ ))    ║
        ///║     \     `-.:.( \)----,A=====|E)-&gt; ║
        ///║      \        / \ \  ,&apos;_3     ||    ║
        ///║       )      / ,&apos;\/.&apos;,&apos;  \    ))    ║
        ///║     /     ,&apos; /   `.&apos;     \  //      ║
        ///║    (   ,-/  (             \//       ║
        ///║     `-&apos; /    \             V        ║
        ///║        &apos;/^;^:^\    [stringa troncata]&quot;;.
        /// </summary>
        internal static string AsciiArt_Ranger {
            get {
                return ResourceManager.GetString("AsciiArt.Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a                   .e$c&quot;*eee...                                                             
        ///                z$$$$$$.  &quot;*$$$$$$$$$.                                                     
        ///            .z$$$$$$$$$$$e. &quot;$$$$$$$$$$c.                                                  
        ///         .e$$P&quot;&quot;  $$  &quot;&quot;*$$$bc.&quot;$$$$$$$$$$$e.                                              
        ///     .e$*&quot;&quot;       $$         &quot;**be$$$***$   3                                              
        ///     $            $F              $    4$r  &apos;F  [stringa troncata]&quot;;.
        /// </summary>
        internal static string AsciiArt_Rest {
            get {
                return ResourceManager.GetString("AsciiArt.Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a     ________________ __                                                          
        ///  | _______________ __ |           _____________________________________         
        ///  ||                  ||          |                                     |        
        ///  ||       ()         ||          |  _|  _.   _       _    _        _   |        
        ///  ||     __)(__       ||          | |_| | |  |_| |_| .-|  `-. | |_| _|_ |        
        ///  ||     &apos;-&lt;&gt;-&apos;       ||          |          |     &apos;  ~    ~  +   |  |  |        
        ///  ||       )(  [stringa troncata]&quot;;.
        /// </summary>
        internal static string AsciiArt_Shop {
            get {
                return ResourceManager.GetString("AsciiArt.Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ╔══════════════════════════════════╗
        ///║    ,   ^           {}            ║
        ///║   / \, | ,        .--.           ║
        ///║  |    =|= &gt;      /.--.\          ║
        ///║   \ /` | `       |====|          ║
        ///║    `   |         |`::`|          ║
        ///║        |     .-;`\..../`;-.      ║
        ///║       /\\/  /  |...::...|  \     ║
        ///║       |:&apos;\ |   /&apos;&apos;&apos;::&apos;&apos;&apos;\   |    ║
        ///║        \ /\;-,/\   ::   /\--;    ║
        ///║        |\ &lt;` &gt;  &gt;._::_.&lt;,&lt;__&gt;    ║
        ///║        | `&quot;&quot;`  /   ^^   \|  |    ║
        ///║        |       |        |\::/    ║
        ///║        |       | [stringa troncata]&quot;;.
        /// </summary>
        internal static string AsciiArt_Warrior {
            get {
                return ResourceManager.GetString("AsciiArt.Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ╔══════════════════════════╗
        ///║                          ║
        ///║               _,-&apos;|      ║
        ///║            ,-&apos;._  |      ║
        ///║  .||,      |####\ |      ║
        ///║ \.`&apos;,/     \####| |      ║
        ///║ = ,. =      |###| |      ║
        ///║ / || \    ,-&apos;\#/,&apos;`.     ║
        ///║   ||     ,&apos;   `,,. `.    ║
        ///║   ,|____,&apos; , ,;&apos; \| |    ║
        ///║  (3|\    _/|/&apos;   _| |    ║
        ///║   ||/,-&apos;&apos;  | &gt;-&apos;&apos; _,\\   ║
        ///║   ||&apos;      ==\ ,-&apos;  ,&apos;   ║
        ///║   ||       |  V \ ,|     ║
        ///║   ||       |    |` |     ║
        ///║   ||       |    |   \    ║
        ///║   ||       |    \    \   ║
        ///║  [stringa troncata]&quot;;.
        /// </summary>
        internal static string AsciiArt_Wizard {
            get {
                return ResourceManager.GetString("AsciiArt.Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giant Bee[PARAM]
        ///Sting_D4,
        ///Bite_D4,
        ///Bee Swarm_D6[PARAM]
        ///      .-.         .--&apos;&apos;-.     
        ///    .&apos;   &apos;.     /&apos;       `.   
        ///    &apos;.     &apos;. ,&apos;          |   
        /// o    &apos;.o   ,&apos;        _.-&apos;    
        ///  \.--./&apos;. /.:. :._:.&apos;        
        /// .\   /&apos;._-&apos;:#0: &apos;:#0: &apos;:     
        ///:(#) (#) :  &apos;:#0: &apos;:#0: &apos;:&gt;#=-
        /// &apos; ____ .&apos;_.:J0:&apos; :J0:&apos; :&apos;    
        ///  &apos;V  V&apos;/ | |&quot;:&apos; :&apos;&quot;:&apos;        
        ///        \  \ \                
        ///        &apos;  &apos; &apos;                
        ///[PARAM].
        /// </summary>
        internal static string bee {
            get {
                return ResourceManager.GetString("bee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crab[PARAM]
        ///Claw_D4,
        ///Bite_D4[PARAM]
        ///               ___     ___             
        ///             .i .-&apos;   `-. i.           
        ///           .&apos;   `/     \&apos;  _`.         
        ///           |,-../ o   o \.&apos; `|         
        ///        (| |   /  _\ /_  \   | |)      
        ///         \\\  (_.&apos;.&apos;&quot;`.`._)  ///       
        ///          \\`._(..:   :..)_.&apos;//        
        ///           \`.__\ .:-:. /__.&apos;/         
        ///            `-i--&gt;.___.&lt;--i-&apos;          
        ///            .&apos;.-&apos;/.=^=.\`-.`.          
        ///           /.&apos;  //     \\  `.\         
        ///          ||   ||      [stringa troncata]&quot;;.
        /// </summary>
        internal static string crab {
            get {
                return ResourceManager.GetString("crab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HealPotion	Flask of Life	A simple medicine	0-0-25	Flask	D4
        ///HealPotion	Wineskin of Life	A wineskin full of life	0-0-50	Canteen	D4
        ///HealPotion	Tonic of Life	This tonic will heal your flesh	0-1-0	Flask	D6
        ///HealPotion	Vial of Rejuvenation	Rejuvenate yourself	0-1-50	Vial	D8
        ///HealPotion	Elixir of Regeneration	This fantastic elixir can really fix you up	0-25-0	Flask	D8
        ///HealPotion	Wineskin of Regeneration	A wineskin full of regeneration elixir	0-50-0	Wineskin	D8
        ///HealPotion	Barrel of Regeneration	A barrel full of [stringa troncata]&quot;;.
        /// </summary>
        internal static string Data_Potions {
            get {
                return ResourceManager.GetString("Data.Potions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sword	Greatsword	A big sword	0-10-0	5	D8	Strength	
        ///Sword	Katana	Sharp and Lethal	1-0-0	3	D12	Dexterity	
        ///Sword	Longsword	Short and handy	0-0-50	3	D6	Strength	
        ///Sword	Broadsword	Wide blade sword	0-1-0	3	D7	Strength	
        ///Sword	Darksword	Its blade is full of dark magic	3-0-0	6	D13	Intelligence	
        ///Sword	Drake Sword	A sword made of dragon scales	3-0-0	8	D14	Strength	
        ///Sword	Blade of Dominance	A sword that demands dominance	0-50-0	5	D10	Charisma	
        ///Sword	Crystal Sword	Shines in the dark	3-50-0	4	D12	Intelligence	
        ///Sw [stringa troncata]&quot;;.
        /// </summary>
        internal static string Data_Weapons {
            get {
                return ResourceManager.GetString("Data.Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gryphon[PARAM]
        ///Beak_D8,
        ///Claws_D12[PARAM]
        ///                           _               
        ///                          _)\.-.           
        ///         .-.__,___,_.-=-. )\`  a`\_        
        ///     .-.__\__,__,__.-=-. `/  \     `\      
        ///     {~,-~-,-~.-~,-,;;;;\ |   &apos;--;`)/      
        ///      \-,~_-~_-,~-,(_(_(;\/   ,;/          
        ///       &quot;,-.~_,-~,-~,)_)_)&apos;.  ;;(           
        ///         `~-,_-~,-~(_(_(_(_\  `;\          
        ///   ,          `&quot;~~--,)_)_)_)\_   \         
        ///   |\              (_(_/_(_,   \  ;        
        ///   \ &apos;-.       _.- [stringa troncata]&quot;;.
        /// </summary>
        internal static string gryphon {
            get {
                return ResourceManager.GetString("gryphon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imp[PARAM]
        ///Claws_D4,
        ///Fireballs_D6,
        ///Fire Punch_D6[PARAM]
        /// *                       * 
        ///    *                 *    
        ///   )       (\___/)     (   
        ///* /(       \ (. .)     )\ *
        ///  # )      c\   &gt;&apos;    ( #  
        ///   &apos;         )-_/      &apos;   
        /// \\|,    ____| |__    ,|// 
        ///   \ )  (  `  ~   )  ( /   
        ///    #\ / /| . &apos; .) \ /#    
        ///    | \ / )   , / \ / |    
        ///     \,/ ;;,,;,;   \,/     
        ///      _,#;,;;,;,           
        ///     /,i;;;,,;#,;          
        ///    //  %;;,;,;;,;         
        ///   ((    ;#;,;%;;,,        
        ///  _//     ;,;; ,# [stringa troncata]&quot;;.
        /// </summary>
        internal static string imp {
            get {
                return ResourceManager.GetString("imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Knight[PARAM]
        ///Sword Slashes_D4,
        ///Sword Thrust_D6,
        ///Shield Strike_D4,
        ///Charge with its shield_D4[PARAM]
        ///  / \                     
        ///  | |                     
        ///  |.|                     
        ///  |.|                     
        ///  |:|      __             
        ///,_|:|_,   /  )            
        ///  (Oo    / _I_            
        ///   +\ \  || __|           
        ///      \ \||___|           
        ///        \ /.:.\-\         
        ///         |.:. /-----\     
        ///         |___|::oOo::|    
        ///         /   |:&lt;_T_&gt;:|    
        ///        |_____\ ::: /     
        ///         | |  \ [stringa troncata]&quot;;.
        /// </summary>
        internal static string knight {
            get {
                return ResourceManager.GetString("knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a do_4_125
        ///mi_4_125
        ///sol_4_125
        ///do_5_125
        ///do_5_125
        ///sol_4_125
        ///mi_4_125
        ///do_4_125.
        /// </summary>
        internal static string Music_BardScale1 {
            get {
                return ResourceManager.GetString("Music.BardScale1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a si_4_125
        ///do_4_125
        ///re_4_125
        ///mi_4_125
        ///fa_4_125
        ///sol_4_125
        ///la_4_125
        ///si_4_125
        ///la_4_250
        ///sol_4_250
        ///mi_4_250.
        /// </summary>
        internal static string Music_BardScale2 {
            get {
                return ResourceManager.GetString("Music.BardScale2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a do_4_125
        ///re_4_125
        ///mi_4_125
        ///fa_4_125
        ///sol_4_125
        ///la_4_125
        ///si_4_125
        ///do_5_125.
        /// </summary>
        internal static string Music_BardScale3 {
            get {
                return ResourceManager.GetString("Music.BardScale3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a re_4_375
        ///re_4_125
        ///re_4_1000
        ///re_4_167
        ///mi_4_167
        ///fa_4_167
        ///la_4_500
        ///sol_4_1500
        ///sol_4_167
        ///sol_4_167
        ///sol_4_167
        ///la_4_167
        ///la_4_167
        ///la_4_167
        ///sib_4_167
        ///sib_4_167
        ///sib_4_167
        ///dod_5_167
        ///re_5_167
        ///mi_5_167
        ///la_4_1500
        ///rest_0_500
        ///re_5_375
        ///re_5_125
        ///re_5_1000
        ///re_5_167
        ///do_5_167
        ///sib_4_167
        ///la_4_500
        ///sol_4_1000
        ///rest_0_500
        ///re_5_167
        ///la_4_167
        ///fa_4_167
        ///la_4_167
        ///fa_4_167
        ///re_4_167
        ///fa_4_167
        ///mi_4_167
        ///re_4_167
        ///mi_4_167
        ///fa_4_167
        ///sol_4_167
        ///mi_4_1500
        ///rest_0_500.
        /// </summary>
        internal static string Music_Besame_Mucho {
            get {
                return ResourceManager.GetString("Music.Besame_Mucho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a re_4_125
        ///si_4_125
        ///la_4_125
        ///sol_4_125
        ///
        ///re_4_375
        ///re_4_62
        ///re_4_62
        ///
        ///re_4_125
        ///si_4_125
        ///la_4_125
        ///sol_4_125
        ///
        ///mi_4_250
        ///rest_0_250
        ///
        ///mi_4_125
        ///do_5_125
        ///si_4_125
        ///la_4_125
        ///
        ///fad_4_375
        ///rest_0_125
        ///
        ///re_5_125
        ///re_5_125
        ///do_5_125
        ///la_4_125
        ///
        ///si_4_250
        ///rest_0_250
        ///
        ///re_4_125
        ///si_4_125
        ///la_4_125
        ///sol_4_125
        ///
        ///re_4_250
        ///rest_0_250
        ///
        ///re_4_125
        ///si_4_125
        ///la_4_125
        ///sol_4_125
        ///
        ///mi_4_250
        ///rest_0_125
        ///mi_4_125
        ///
        ///mi_4_125
        ///do_5_125
        ///si_4_125
        ///la_4_125
        ///
        ///re_5_125
        ///re_5_125
        ///re_5_125
        ///re_5_125
        ///
        ///mi_5_125
        ///r [stringa troncata]&quot;;.
        /// </summary>
        internal static string Music_JingleBells {
            get {
                return ResourceManager.GetString("Music.JingleBells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FaD_4_250
        ///DoD_4_125
        ///Re_4_125
        ///Mi_4_125
        ///FaD_4_62
        ///Mi_4_62
        ///Re_4_125
        ///DoD_4_125
        ///Si_3_250
        ///Si_3_125
        ///Re_4_125
        ///FaD_4_250
        ///Mi_4_125
        ///Re_4_125
        ///DoD_4_375
        ///Re_4_125
        ///Mi_4_250
        ///FaD_4_250
        ///Re_4_250
        ///Si_3_250
        ///Si_3_250
        ///Rest_0_375
        ///Mi_4_350
        ///Sol_4_125
        ///Si_4_250
        ///La_4_125
        ///Sol_4_125
        ///FaD_4_375
        ///Re_4_125
        ///FaD_4_250
        ///Mi_4_125
        ///Re_4_125
        ///DoD_4_250
        ///DoD_4_125
        ///Re_4_125
        ///Mi_4_250
        ///FaD_4_250
        ///Re_4_250
        ///Si_3_250
        ///Si_3_250
        ///Rest_0_250.
        /// </summary>
        internal static string Music_Tetris {
            get {
                return ResourceManager.GetString("Music.Tetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scorpion[PARAM]
        ///Sting_D4,
        ///Pinch_D4,
        ///Venomous Pinch_D6[PARAM]
        /// ___    ___     
        ///( _&lt;    &gt;_ )    
        /////        \\    
        ///\\___..___//    
        /// `-(    )-&apos;     
        ///   _|__|_       
        ///  /_|__|_\      
        ///  /_|__|_\      
        ///  /_\__/_\      
        ///   \ || /  _)   
        ///     ||   ( )   
        ///     \\___//    
        ///      `---&apos;     
        ///[PARAM].
        /// </summary>
        internal static string scorpion {
            get {
                return ResourceManager.GetString("scorpion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giant Spider Wolf[PARAM]
        ///Spider Climb_D4,
        ///Bite_D6,
        ///Web Throwing_D4[PARAM]
        ///           ____                      ,       
        ///          /---.&apos;.__             ____//       
        ///               &apos;--.\           /.---&apos;        
        ///          _______  \\         //             
        ///        /.------.\  \|      .&apos;/  ______      
        ///       //  ___  \ \ ||/|\  //  _/_----.\__   
        ///      |/  /.-.\  \ \:|&lt; &gt;|// _/.&apos;..\   &apos;--&apos;  
        ///         //   \&apos;. | \&apos;.|.&apos;/ /_/ /  \\        
        ///        //     \ \_\/&quot; &apos; ~\-&apos;.-&apos;    \\       
        ///       //   [stringa troncata]&quot;;.
        /// </summary>
        internal static string spider {
            get {
                return ResourceManager.GetString("spider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wolf[PARAM]
        ///Bite_D6,
        ///Claws_D6,
        ///Vicious Bite_D8[PARAM]
        ///                        ,     ,
        ///                        |\---/|
        ///                       /  , , |
        ///                  __.-&apos;|  / \ /
        ///         __ ___.-&apos;        ._O| 
        ///      .-&apos;  &apos;        :      _/  
        ///     / ,    .        .     |   
        ///    :  ;    :        :   _/    
        ///    |  |   .&apos;     __:   /      
        ///    |  :   /&apos;----&apos;| \  |       
        ///    \  |\  |      | /| |       
        ///     &apos;.&apos;| /       || \ |       
        ///     | /|.&apos;       &apos;.l \\_      
        ///     || ||             &apos;- [stringa troncata]&quot;;.
        /// </summary>
        internal static string wolf {
            get {
                return ResourceManager.GetString("wolf", resourceCulture);
            }
        }
    }
}
